---
title: "ILORA"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ILORA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction to ILORA Package

## Overview

The ILORA (Indian Alien Flora Information) package is designed to facilitate the retrieval and analysis of species occurrence data from the Indian Alien Flora Information (ILORA) database. This vignette provides an introduction to using the ILORA package, including retrieving species data, accessing variable information, and utilizing the package's functions.

## Installation

You can install the ILORA package from CRAN using the following command:

```r
install.packages("ILORA")
```

Alternatively, you can install the development version from GitHub:

```r
devtools::install_github("Ruqaiya41/ILORA")
```
Once installed, load the ILORA package into your R session:

```r
library(ILORA)
```

# Functions Provided

The ILORA package provides several functions to facilitate data retrieval and analysis:

- `get_species_names`: Retrieves example species names available in the ILORA database.
- `get_variable_names`: Retrieves example variable names relevant to species data analysis.
- `retrieve_species_data`: Retrieves data for a given species from the ILORA database based on specified variables.


### Retrieving Species Names

To retrieve example species names from the ILORA package:

```r
species <- get_species_names()
head(species)
```


### Retrieving Variable Names

To retrieve variable names from the ILORA package:

```r
variable <- get_variable_names()
head(variable)
```

### Retrieving Data from Database

To retrieve data for a specific species and variable from the ILORA package:

```r
species_data <- retrieve_species_data("Rotala densiflora (Roth) Koehne", c("orders", "0700_Fuels2", "genus", "species"))
head(species_data)
```
